---
title: "PatternDiscoveryTools"
author: "Kirsten Frank"
date: "February 22, 2015"
output: html_document
---

Coursera Course Pattern Discovery in Data Mining. I am TAing this course and I want to implement some of the tools in R.


```{r Generate small basket}
set.seed(123)
Itemlist<-c("Beer","Coffee","Nuts","Diapers","Milk","Bread","Wine","Cheese","HotDogs","Steak","Ketchup","Mustard")
library(arules)
N<-80   #Number of transactions
size_transaction<-sample(2:10,N,replace=TRUE)
DB<-list()
for (i in 1:length(size_transaction))
    {
    newtransactionDB<-sample(Itemlist,size_transaction[i],replace=FALSE)
    DB[i]<-list(newtransactionDB)
}

##This finally works. It generates N transactions from the ItemList without duplicates.

transDB<-as(DB,"transactions")  ##Convert to a Matrix that Arules expects.

freqset <-eclat(transDB, parameter=
                    list(support=0.30, minlen =1))
## find frequent itemsets using ECLAT algorithm

inspect(freqset)

rules<-apriori(transDB,parameter=
                   list(support=0.30,
                        confidence =0.4,
                        minlen =2))

inspect(rules)
```

You can also embed plots, for example:

```{r subset or sort rules}
inspect(sort(rules, by = "confidence"))
rules.sub<-subset(rules,subset=confidence > 0.64)
interestMeasure(rules,method=c("cosine","chiSquared"),transDB)
```

